# Generated by Django 5.2.7 on 2025-11-03 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_pedido_nuevo', models.BooleanField(default=True)),
                ('notif_pedido_confirmado', models.BooleanField(default=True)),
                ('notif_pedido_listo', models.BooleanField(default=True)),
                ('notif_pedido_en_camino', models.BooleanField(default=True)),
                ('notif_pedido_completado', models.BooleanField(default=True)),
                ('notif_promociones', models.BooleanField(default=True)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_push', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido_nuevo', 'Nuevo Pedido'), ('pedido_confirmado', 'Pedido Confirmado'), ('pedido_preparando', 'Pedido en Preparación'), ('pedido_listo', 'Pedido Listo'), ('pedido_en_camino', 'Pedido en Camino'), ('pedido_completado', 'Pedido Completado'), ('pedido_cancelado', 'Pedido Cancelado'), ('stock_bajo', 'Stock Bajo'), ('sistema', 'Notificación del Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx')],
            },
        ),
    ]
