# Generated by Django 5.2.7 on 2025-11-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transaccion', models.CharField(editable=False, max_length=100, unique=True)),
                ('metodo_pago', models.CharField(choices=[('webpay', 'WebPay'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('token_ws', models.CharField(blank=True, max_length=100)),
                ('orden_compra', models.CharField(blank=True, max_length=100)),
                ('numero_transferencia', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('banco_origen', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('datos_respuesta', models.JSONField(blank=True, help_text='Respuesta del gateway de pago', null=True)),
                ('notas', models.TextField(blank=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pagos.pago')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['codigo_transaccion'], name='pagos_pago_codigo__cfdce9_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['pedido', 'estado'], name='pagos_pago_pedido__894435_idx'),
        ),
    ]
