# Generated by Django 5.2.7 on 2025-11-09 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['usuario', 'negocio', 'activo'], name='carrito_car_usuario_fbff6f_idx'),
        ),
    ]
