# Generated by Django 5.2.7 on 2025-11-09 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carrito_unique_together_and_more'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario', 'negocio'), name='unique_carrito_activo_por_usuario_negocio'),
        ),
    ]
