# Generated by Django 5.2.7 on 2025-11-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carrito_unique_carrito_activo_por_usuario_negocio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carrito',
            name='unique_carrito_activo_por_usuario_negocio',
        ),
        migrations.RemoveIndex(
            model_name='carrito',
            name='carrito_car_usuario_fbff6f_idx',
        ),
    ]
