# Generated by Django 5.2.7 on 2025-11-21 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('puntos_requeridos', models.IntegerField()),
                ('stock', models.IntegerField(default=-1)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='premios/')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'ordering': ['puntos_requeridos'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Programa Pick Up Rural', max_length=100)),
                ('descripcion', models.TextField(default='Acumula puntos con tus compras y canjéalos por premios')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('puntos_por_peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('puntos_minimos_canje', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Programa de Fidelidad',
                'verbose_name_plural': 'Programas de Fidelidad',
            },
        ),
        migrations.CreateModel(
            name='ClienteFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('puntos_canjeados', models.IntegerField(default=0)),
                ('nivel', models.CharField(choices=[('bronce', '🥉 Bronce'), ('plata', '🥈 Plata'), ('oro', '🥇 Oro'), ('diamante', '💎 Diamante')], default='bronce', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fidelidad', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.programafidelidad')),
            ],
            options={
                'verbose_name': 'Cliente Fidelidad',
                'verbose_name_plural': 'Clientes Fidelidad',
            },
        ),
        migrations.CreateModel(
            name='CanjePuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_usados', models.IntegerField()),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('cliente_fidelidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='fidelizacion.clientefidelidad')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.premio')),
            ],
            options={
                'verbose_name': 'Canje de Puntos',
                'verbose_name_plural': 'Canjes de Puntos',
                'ordering': ['-fecha_canje'],
            },
        ),
        migrations.AddField(
            model_name='premio',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='fidelizacion.programafidelidad'),
        ),
    ]
