# Generated by Django 5.2.7 on 2025-11-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Alerta de stock bajo')),
                ('unidad_medida', models.CharField(default='unidad', help_text='Ej: kg, litros, unidad', max_length=20)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en gramos', max_digits=8, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='usuarios.negocio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='productos_p_codigo_bbe51f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['negocio', 'activo'], name='productos_p_negocio_c7cc76_idx'),
        ),
    ]
