# Generated by Django 5.2.7 on 2025-11-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='requiere_embalaje_especial',
            field=models.BooleanField(default=False, help_text='Requiere hielo o embalaje especial'),
        ),
        migrations.AddField(
            model_name='producto',
            name='temperatura_ideal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura Ideal (°C)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_almacenamiento',
            field=models.CharField(choices=[('ambiente', '🌡️ Temperatura Ambiente'), ('refrigerado', '❄️ Refrigerado (2-8°C)'), ('congelado', '🧊 Congelado (-18°C)'), ('fresco', '🥬 Fresco (caducidad corta)')], default='ambiente', max_length=20, verbose_name='Requisito de Almacenamiento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vida_util_horas',
            field=models.IntegerField(blank=True, help_text='Vida útil en horas desde preparación', null=True),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo_almacenamiento'], name='productos_p_tipo_al_dccd4b_idx'),
        ),
    ]
